from __future__ import annotations

from app.services.agent_orchestrator.types import TablePolicy


POLICIES: dict[str, TablePolicy] = {
    "categories": TablePolicy(
        table_name="categories",
        business_name="financial categories available to the current user",
        allowed_select=True,
        allowed_insert=False,
        user_scoped=False,
        selectable_columns={"id", "name", "icon", "color", "is_default", "user_id"},
        forbidden_columns=set(),
        max_select_rows=50,
    ),
    "transactions": TablePolicy(
        table_name="transactions",
        business_name="current user's income and expense transactions",
        allowed_select=True,
        allowed_insert=True,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={"id", "category_id", "amount", "type", "description", "date", "created_at"},
        insertable_columns={"category_id", "amount", "type", "description", "date"},
        forbidden_columns={"user_id"},
        max_select_rows=100,
    ),
    "budgets": TablePolicy(
        table_name="budgets",
        business_name="current user's monthly budget records",
        allowed_select=True,
        allowed_insert=False,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={"id", "month", "year", "amount", "currency"},
        forbidden_columns={"user_id"},
        max_select_rows=24,
    ),
    "goals": TablePolicy(
        table_name="goals",
        business_name="current user's savings and purchase goals",
        allowed_select=True,
        allowed_insert=True,
        allowed_update=True,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={"id", "title", "target_amount", "current_amount", "deadline", "status", "is_active", "notes_json", "created_at", "updated_at"},
        insertable_columns={"title", "target_amount", "current_amount", "deadline", "status", "is_active", "notes_json"},
        updateable_columns={"title", "target_amount", "current_amount", "deadline", "status", "is_active", "notes_json"},
        forbidden_columns={"user_id"},
        max_select_rows=50,
    ),
    "future_commitments": TablePolicy(
        table_name="future_commitments",
        business_name="current user's future payments, obligations, and planned commitments",
        allowed_select=True,
        allowed_insert=True,
        allowed_update=True,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={
            "id",
            "title",
            "amount",
            "due_date",
            "due_month",
            "category_id",
            "related_transaction_id",
            "related_goal_id",
            "description",
            "status",
            "source",
            "metadata_json",
            "created_at",
            "updated_at",
        },
        insertable_columns={
            "title",
            "amount",
            "due_date",
            "due_month",
            "category_id",
            "related_transaction_id",
            "related_goal_id",
            "description",
            "status",
            "source",
            "metadata_json",
        },
        updateable_columns={"title", "amount", "due_date", "due_month", "category_id", "related_transaction_id", "related_goal_id", "description", "status", "metadata_json"},
        forbidden_columns={"user_id"},
        max_select_rows=50,
    ),
    "chat_messages": TablePolicy(
        table_name="chat_messages",
        business_name="limited current chat history",
        allowed_select=True,
        allowed_insert=False,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={"id", "role", "content", "created_at"},
        forbidden_columns={"user_id"},
        max_select_rows=20,
        system_only=True,
    ),
    "users": TablePolicy(
        table_name="users",
        business_name="minimal current user profile",
        allowed_select=True,
        allowed_insert=False,
        user_scoped=True,
        user_id_column="id",
        selectable_columns={"id", "name", "first_name", "last_name", "language", "income_range", "monthly_income", "chat_mode"},
        forbidden_columns={
            "phone",
            "is_blocked",
            "created_at",
            "agreement_accepted_at",
            "agreement_version",
            "onboarding_completed",
            "onboarding_completed_at",
        },
        max_select_rows=1,
    ),
    "activity_logs": TablePolicy(
        table_name="activity_logs",
        business_name="system activity log",
        system_only=True,
    ),
    "agent_sql_audit_logs": TablePolicy(
        table_name="agent_sql_audit_logs",
        business_name="system audit log for agent database operations",
        system_only=True,
    ),
    "financial_personas": TablePolicy(
        table_name="financial_personas",
        business_name="current user's Personal CFO persona summary",
        allowed_select=True,
        allowed_insert=False,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={
            "id",
            "financial_literacy_level",
            "risk_tolerance",
            "financial_anxiety_level",
            "decision_style",
            "time_horizon",
            "debt_sensitivity",
            "discipline_score",
            "saving_preference",
            "emotional_spending_triggers_json",
            "notes_json",
            "confidence",
            "created_at",
            "updated_at",
        },
        forbidden_columns={"user_id"},
        max_select_rows=1,
    ),
    "financial_memories": TablePolicy(
        table_name="financial_memories",
        business_name="durable user-scoped financial memories",
        allowed_select=True,
        allowed_insert=True,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={"id", "memory_type", "title", "content_json", "source", "confidence", "is_active", "created_at", "updated_at"},
        insertable_columns={"memory_type", "title", "content_json", "source", "confidence"},
        forbidden_columns={"user_id"},
        max_select_rows=10,
    ),
    "behavior_insights": TablePolicy(
        table_name="behavior_insights",
        business_name="active user-scoped financial behavior insights",
        allowed_select=True,
        allowed_insert=True,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={"id", "insight_type", "evidence_json", "confidence", "first_detected_at", "last_detected_at", "is_active"},
        insertable_columns={"insight_type", "evidence_json", "confidence"},
        forbidden_columns={"user_id"},
        max_select_rows=10,
    ),
    "financial_facts": TablePolicy(
        table_name="financial_facts",
        business_name="structured durable financial facts extracted from conversation",
        allowed_select=True,
        allowed_insert=True,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={"id", "fact_type", "subject", "value_json", "confidence", "valid_from", "valid_to", "created_at", "updated_at", "is_active"},
        insertable_columns={"fact_type", "subject", "value_json", "confidence", "valid_from", "valid_to", "is_active"},
        forbidden_columns={"user_id", "source_message_id"},
        max_select_rows=10,
    ),
    "financial_warnings": TablePolicy(
        table_name="financial_warnings",
        business_name="foundation table for user financial warnings",
        allowed_select=True,
        allowed_insert=True,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={"id", "warning_type", "severity", "message", "evidence_json", "status", "created_at", "resolved_at"},
        insertable_columns={"warning_type", "severity", "message", "evidence_json", "status"},
        forbidden_columns={"user_id"},
        max_select_rows=10,
    ),
    "financial_decision_logs": TablePolicy(
        table_name="financial_decision_logs",
        business_name="foundation table for important user financial decision records",
        allowed_select=True,
        allowed_insert=True,
        user_scoped=True,
        user_id_column="user_id",
        selectable_columns={"id", "decision_title", "decision_type", "input_json", "analysis_json", "created_at"},
        insertable_columns={"decision_title", "decision_type", "input_json", "analysis_json"},
        forbidden_columns={"user_id"},
        max_select_rows=10,
    ),
    "persona_update_logs": TablePolicy(
        table_name="persona_update_logs",
        business_name="system persona update audit log",
        system_only=True,
    ),
    "admin_users": TablePolicy(
        table_name="admin_users",
        business_name="admin authentication records",
        system_only=True,
    ),
}


FORBIDDEN_TABLES = {
    "admin_users",
    "activity_logs",
    "agent_sql_audit_logs",
    "persona_update_logs",
    "token_wallets",
    "token_usage_logs",
    "token_purchases",
    "user_subscriptions",
}


def get_policy(table_name: str) -> TablePolicy | None:
    return POLICIES.get(table_name.lower())


def llm_visible_policies() -> list[TablePolicy]:
    return [
        policy
        for policy in POLICIES.values()
        if not policy.system_only and (policy.allowed_select or policy.allowed_insert)
    ]
